export type DomainErrorCode =
  | "INVALID_ID"
  | "DUPLICATE_PARTICIPANT"
  | "NO_PARTICIPANTS"
  | "INVALID_POISHA"
  | "NON_POSITIVE_EXPENSE_AMOUNT"
  | "MONEY_OVERFLOW"
  | "INVALID_MONEY_TEXT"
  | "INVALID_BASIS_POINTS"
  | "INVALID_PERCENTAGE_TEXT"
  | "PERCENTAGE_TOTAL_NOT_100"
  | "MISSING_SPLIT_ENTRY"
  | "UNKNOWN_SPLIT_PARTICIPANT"
  | "NEGATIVE_SPLIT_SHARE"
  | "AMOUNT_SPLIT_TOTAL_MISMATCH"
  | "INVALID_EXPENSE_DATE"
  | "PAYER_CREATOR_MISMATCH"
  | "ALLOCATION_TOTAL_MISMATCH"
  | "INVALID_INSTANT"
  | "UNKNOWN_BALANCE_MEMBER"
  | "BALANCE_OVERFLOW"
  | "BALANCE_SHEET_NOT_ZERO_SUM"
  | "INVALID_EXPENSE_LEDGER_ENTRY"
  | "INVALID_SETTLEMENT_PARTIES"
  | "SETTLEMENT_MEMBER_INACTIVE"
  | "SETTLEMENT_NOT_RECOMMENDED"
  | "SETTLEMENT_AMOUNT_MISMATCH"
  | "DUPLICATE_PENDING_SETTLEMENT"
  | "SETTLEMENT_NOT_PENDING"
  | "SETTLEMENT_ACTOR_NOT_SENDER"
  | "SETTLEMENT_ACTOR_NOT_RECEIVER"
  | "INVALID_SETTLEMENT_TRANSITION"
  | "CONFIRMED_SETTLEMENT_IMMUTABLE"
  | "NOT_ACTIVE_HOUSEHOLD_MEMBER"
  | "EXPENSE_VIEW_FORBIDDEN"
  | "EXPENSE_EDIT_FORBIDDEN"
  | "EXPENSE_DELETE_FORBIDDEN"
  | "PRIVATE_CARD_ACCESS_FORBIDDEN"
  | "FORMER_MEMBER_FINANCIAL_HISTORY_FROZEN"
  | "MEMBER_BALANCE_NOT_ZERO"
  | "MEMBER_HAS_PENDING_SETTLEMENT"
  | "LEADER_TRANSFER_REQUIRED"
  | "LEADER_MUST_DELETE_HOUSEHOLD"
  | "LEADERSHIP_TRANSFER_FORBIDDEN"
  | "MEMBER_REMOVAL_FORBIDDEN"
  | "HOUSEHOLD_DELETE_FORBIDDEN"
  | "INVALID_HOUSEHOLD_MEMBERSHIP";

export class DomainError extends Error {
  readonly code: DomainErrorCode;

  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = "DomainError";
    this.code = code;
  }
}
